language: php

php:
  - 7.0
  - nightly

env:
  - CMD='phpdbg -qrr vendor/bin/phpspec'
  - CMD='vendor/bin/phpspec'

before_script:
 - composer install --no-interaction --optimize-autoloader

script:
 - $CMD run --format=pretty --no-interaction --verbose
