language: php

php:
  - 7.0
  - nightly

before_script:
 - composer install --no-interaction --optimize-autoloader

script:
 - phpdbg -qrr vendor/bin/phpspec run --format=pretty --no-interaction --verbose
