language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

before_script:
 - composer install --no-interaction --optimize-autoloader

script:
 - vendor/bin/phpspec run --format=pretty --no-interaction --verbose
